import json

tr_add = {
  "medicalScreeningTitle": "Tıbbi Tarama",
  "medicalScreeningExclusionCriteria": "Dışlama Kriterleri: Bu uygulama genel sağlıklı bireyler içindir. Herhangi bir soruyu \"Evet\" olarak yanıtlarsanız, egzersiz programına başlamadan önce mutlaka doktorunuza danışmalısınız.",
  "stepTracker": "Adım {step}/3",
  "@stepTracker": { "placeholders": { "step": { "type": "int" } } },
  "saveProgress": "İlerlemeyi\nKaydet",
  "completeBtn": "Tamamla",
  "continueBtn": "Devam Et",
  "pleaseAnswerAllQuestions": "Lütfen tüm soruları yanıtlayın.",
  "progressSaved": "İlerleme kaydedildi.",
  "medicalWarningTitle": "Tıbbi Uyarı",
  "screeningCompletedTitle": "Tarama Tamamlandı",
  "medicalWarningDescP1": "Güvenliğiniz bizim için önemli. Verdiğiniz yanıtlara göre, bu egzersiz programına başlamadan önce bir sağlık profesyoneline danışmanız gerekmektedir. ",
  "deskRelief": "DeskRelief",
  "medicalWarningDescP2": ", tıbbi bir tanı veya tedavi aracı değildir.",
  "screeningSuccessDesc": "Harika! Egzersiz programına başlamak için herhangi bir tıbbi engeliniz bulunmuyor. Şimdi ağrı bölgelerinizi seçerek size özel programınızı oluşturabiliriz.",
  "understood": "Anladım",
  "qCat1": "Sistemik ve Kalp Sağlığı",
  "qCat2": "Kas-İskelet ve Travma",
  "qCat3": "Kırmızı Bayraklar",
  "q1": "Daha önce size tanı konmuş inme (beyin kanaması/felç) öykünüz var mı?",
  "q2": "Kalp yetmezliği, kalp krizi, kalp ritm bozukluğu veya ciddi bir kalp-damar hastalığınız var mı?",
  "q3": "Doktorunuz size egzersiz yapmamanız gerektiğini söyledi mi?",
  "q4": "İstirahatte veya hafif aktivite sırasında göğüs ağrısı, nefes darlığı, baş dönmesi ya da bayılma yaşıyor musunuz?",
  "q5": "Tanı konmuş ciddi bir solunum hastalığınız var mı? (örn: Astım, KOAH)",
  "q6": "Tanı konmuş bir nörolojik hastalığınız var mı? (örn: Parkinson hastalığı, Multipl skleroz)",
  "q7": "Aktif kanser tedavisi görüyor musunuz?",
  "q8": "Son 6 ay içinde ameliyat geçirdiniz mi?",
  "q9": "Son 6 ayda ciddi bir kas-iskelet sistemi yaralanması yaşadınız mı?",
  "q10": "Son dönemde hastanede yatış gerektiren bir sağlık sorunu yaşadınız mı?",
  "q11": "Tanı konmuş yüksek tansiyonunuz var mı (Hipertansiyon)?",
  "q12": "Doktor tarafından tanı konmuş bel fıtığı, boyun fıtığı veya diz probleminiz var mı?",
  "q13": "Gece uykudan uyandıran ağrınız var mı?",
  "q14": "Açıklanamayan kilo kaybınız oldu mu?",
  "q15": "Yakın zamanda düşme, çarpma gibi bir travma sonrası başlayan ağrınız var mı?",
  "q16": "İlerleyici kas güçsüzlüğü, uyuşma veya his kaybı yaşıyor musunuz?",
  "q17": "Hamile misiniz veya hamile olma ihtimaliniz var mı?",
  "q18": "Daha önce egzersiz yaptıktan sonra uzun süren (24-48 saatten fazla) aşırı ağrı veya kötüleşme yaşadınız mı?",
  "yes": "Evet",
  "no": "Hayır"
}

en_add = {
  "medicalScreeningTitle": "Medical Screening",
  "medicalScreeningExclusionCriteria": "Exclusion Criteria: This app is for generally healthy individuals. If you answer \"Yes\" to any question, you must consult your doctor before starting an exercise program.",
  "stepTracker": "Step {step}/3",
  "@stepTracker": { "placeholders": { "step": { "type": "int" } } },
  "saveProgress": "Save\nProgress",
  "completeBtn": "Complete",
  "continueBtn": "Continue",
  "pleaseAnswerAllQuestions": "Please answer all questions.",
  "progressSaved": "Progress saved.",
  "medicalWarningTitle": "Medical Warning",
  "screeningCompletedTitle": "Screening Completed",
  "medicalWarningDescP1": "Your safety is important to us. Based on your answers, you should consult a healthcare professional before starting this exercise program. ",
  "deskRelief": "DeskRelief",
  "medicalWarningDescP2": " is not a medical diagnosis or treatment tool.",
  "screeningSuccessDesc": "Great! You have no medical barriers to starting the exercise program. Now we can create your customized program by selecting your pain regions.",
  "understood": "I Understand",
  "qCat1": "Systemic and Heart Health",
  "qCat2": "Musculoskeletal and Trauma",
  "qCat3": "Red Flags",
  "q1": "Do you have a history of a diagnosed stroke (brain hemorrhage/paralysis)?",
  "q2": "Do you have heart failure, heart attack, arrhythmia, or a serious cardiovascular disease?",
  "q3": "Has your doctor told you that you should not exercise?",
  "q4": "Do you experience chest pain, shortness of breath, dizziness, or fainting at rest or during light activity?",
  "q5": "Do you have a diagnosed serious respiratory disease? (e.g., Asthma, COPD)",
  "q6": "Do you have a diagnosed neurological disease? (e.g., Parkinson's disease, Multiple sclerosis)",
  "q7": "Are you currently receiving active cancer treatment?",
  "q8": "Have you had surgery in the last 6 months?",
  "q9": "Have you experienced a serious musculoskeletal injury in the last 6 months?",
  "q10": "Have you recently experienced a health issue that required hospitalization?",
  "q11": "Do you have diagnosed high blood pressure (Hypertension)?",
  "q12": "Do you have a doctor-diagnosed herniated disc in your lower back or neck, or a knee problem?",
  "q13": "Do you have pain that wakes you up from sleep at night?",
  "q14": "Have you experienced unexplained weight loss?",
  "q15": "Do you have pain that started after a recent trauma such as a fall or impact?",
  "q16": "Are you experiencing progressive muscle weakness, numbness, or loss of sensation?",
  "q17": "Are you pregnant or is there a possibility that you might be pregnant?",
  "q18": "Have you previously experienced excessive pain or worsening that lasted long (more than 24-48 hours) after exercising?",
  "yes": "Yes",
  "no": "No"
}

for file, items in [("lib/l10n/app_tr.arb", tr_add), ("lib/l10n/app_en.arb", en_add)]:
    with open(file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    data.update(items)
    with open(file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
