import json

tr_add = {
  "bodyMapTitle": "Ağrı Haritası",
  "bodyMapDesc": "Son üç aydır kronik ağrı yaşadığınız bölgeleri haritadan belirleyin.",
  "front": "Ön",
  "back": "Arka",
  "selectedRegionsTitle": "Seçilen Bölgeler",
  "bodyMapEmptyState": "Ağrı hissettiğiniz bölgeleri harita üzerinden dokunarak seçiniz.",
  "determinePainIntensity": "AĞRI ŞİDDETİNİ BELİRLE",
  "regionShoulderRight": "Sağ Omuz",
  "regionShoulderLeft": "Sol Omuz",
  "regionHipPelvis": "Kalça",
  "regionArmRight": "Sağ El/Dirsek/Bilek",
  "regionArmLeft": "Sol El/Dirsek/Bilek",
  "regionKneeRight": "Sağ Diz",
  "regionKneeLeft": "Sol Diz",
  "regionAnkleRight": "Sağ Ayak Bileği",
  "regionAnkleLeft": "Sol Ayak Bileği",
  "noRegionSelected": "Seçili bölge bulunamadı.",
  "goBack": "Geri Dön",
  "regionLabel": "{region} Bölgesi",
  "@regionLabel": { "placeholders": { "region": { "type": "String" } } },
  "assessmentPurposeTitle": "Değerlendirme Amacı",
  "assessmentPurposeDesc": "Ağrı şiddeti değerlendirmesi, mevcut durumunuzu objektif bir şekilde takip etmemize ve size en uygun egzersiz yoğunluğunu belirlememize yardımcı olur.",
  "painAnalysisTitle": "Ağrı Analizi",
  "finishAssessment": "DEĞERLENDİRMEYİ BİTİR",
  "nextRegion": "SONRAKİ BÖLGE",
  "focusRegionsTitle": "Odak Bölgeler\nBelirlendi",
  "focusRegionsDescP1": "Algoritmamız en yüksek ağrı skoruna sahip bölgelere öncelik vermiştir: ",
  "focusRegionsDescP2": ".\n\nDiğer bölgeleriniz için, mevcut programı tamamladıktan sonra yeni bir değerlendirme yapabilirsiniz.",
  "focusRegionsBtn": "Tamam, Devam Et",
  "medicalConsultationTitle": "Tıbbi Danışmanlık\nÖnerisi",
  "medicalConsultationDesc": "Vücudunuzun çok sayıda farklı bölgesinde yaygın ve şiddetli ağrılar belirttiğinizi fark ettik.\n\nBu durum \"Merkezi Duyarlılaşma\" veya benzeri bir sendromun belirtisi olabilir. Herhangi bir egzersiz programına başlamadan önce bir hekime danışmanızı önemle tavsiye ederiz.",
  "medicalConsultationBtn": "Anladım",
  "painLevelLight": "Hafif",
  "painLevelMild": "Hafif-Orta",
  "painLevelModerate": "Orta Şiddetli",
  "painLevelSevere": "Şiddetli",
  "painLevelVerySevere": "Çok Şiddetli",
  "painAnalysisLight": "Seviye {val}, günlük hayatı pek etkilemeyen hafif bir ağrıdır. Hareketlilikle düzelebilir.",
  "@painAnalysisLight": { "placeholders": { "val": { "type": "int" } } },
  "painAnalysisMild": "Seviye {val}, hissedilen ancak katlanılabilir bir ağrıdır. Esneme hareketleri faydalı olacaktır.",
  "@painAnalysisMild": { "placeholders": { "val": { "type": "int" } } },
  "painAnalysisModerate": "Seviye {val}, dikkat edilmesi gereken orta şiddetli bir ağrıdır. Kuvvet ve esneklik dengesi hedeflenecektir.",
  "@painAnalysisModerate": { "placeholders": { "val": { "type": "int" } } },
  "painAnalysisSevere": "Seviye {val}, aktiviteleri kısıtlayan şiddetli bir ağrıdır. Kontrollü ve nazik egzersizler gereklidir.",
  "@painAnalysisSevere": { "placeholders": { "val": { "type": "int" } } },
  "painAnalysisVerySevere": "Seviye {val}, çok şiddetli bir ağrıdır. Uzman kontrolünde ilerlemek ve dinlenmek önemlidir.",
  "@painAnalysisVerySevere": { "placeholders": { "val": { "type": "int" } } }
}

en_add = {
  "bodyMapTitle": "Pain Map",
  "bodyMapDesc": "Identify the regions where you have experienced chronic pain for the last three months on the map.",
  "front": "Front",
  "back": "Back",
  "selectedRegionsTitle": "Selected Regions",
  "bodyMapEmptyState": "Select the regions where you feel pain by tapping on the map.",
  "determinePainIntensity": "DETERMINE PAIN INTENSITY",
  "regionShoulderRight": "Right Shoulder",
  "regionShoulderLeft": "Left Shoulder",
  "regionHipPelvis": "Hip",
  "regionArmRight": "Right Hand/Elbow/Wrist",
  "regionArmLeft": "Left Hand/Elbow/Wrist",
  "regionKneeRight": "Right Knee",
  "regionKneeLeft": "Left Knee",
  "regionAnkleRight": "Right Ankle",
  "regionAnkleLeft": "Left Ankle",
  "noRegionSelected": "No selected region found.",
  "goBack": "Go Back",
  "regionLabel": "{region} Region",
  "@regionLabel": { "placeholders": { "region": { "type": "String" } } },
  "assessmentPurposeTitle": "Assessment Purpose",
  "assessmentPurposeDesc": "Pain intensity assessment helps us objectively track your current condition and determine the most appropriate exercise intensity for you.",
  "painAnalysisTitle": "Pain Analysis",
  "finishAssessment": "FINISH ASSESSMENT",
  "nextRegion": "NEXT REGION",
  "focusRegionsTitle": "Focus Regions\nDetermined",
  "focusRegionsDescP1": "Our algorithm has prioritized the regions with the highest pain scores: ",
  "focusRegionsDescP2": ".\n\nFor your other regions, you can make a new assessment after completing the current program.",
  "focusRegionsBtn": "Okay, Continue",
  "medicalConsultationTitle": "Medical Consultation\nRecommendation",
  "medicalConsultationDesc": "We noticed that you reported widespread and severe pain in many different areas of your body.\n\nThis may be a symptom of \"Central Sensitization\" or a similar syndrome. We strongly advise you to consult a physician before starting any exercise program.",
  "medicalConsultationBtn": "I Understand",
  "painLevelLight": "Mild",
  "painLevelMild": "Mild-Moderate",
  "painLevelModerate": "Moderate",
  "painLevelSevere": "Severe",
  "painLevelVerySevere": "Very Severe",
  "painAnalysisLight": "Level {val} is a mild pain that does not significantly affect daily life. It can improve with mobility.",
  "@painAnalysisLight": { "placeholders": { "val": { "type": "int" } } },
  "painAnalysisMild": "Level {val} is a noticeable but tolerable pain. Stretching exercises will be beneficial.",
  "@painAnalysisMild": { "placeholders": { "val": { "type": "int" } } },
  "painAnalysisModerate": "Level {val} is a moderate pain that requires attention. Strength and flexibility balance will be targeted.",
  "@painAnalysisModerate": { "placeholders": { "val": { "type": "int" } } },
  "painAnalysisSevere": "Level {val} is a severe pain that restricts activities. Controlled and gentle exercises are necessary.",
  "@painAnalysisSevere": { "placeholders": { "val": { "type": "int" } } },
  "painAnalysisVerySevere": "Level {val} is a very severe pain. It is important to proceed under expert supervision and rest.",
  "@painAnalysisVerySevere": { "placeholders": { "val": { "type": "int" } } }
}

for file, items in [("lib/l10n/app_tr.arb", tr_add), ("lib/l10n/app_en.arb", en_add)]:
    with open(file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    data.update(items)
    with open(file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
