// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1XmvZFf_3DkCuYG6MGHdalJbswfNy9ZI',
    appId: '1:628797668046:android:12cec9b725084509582e9f',
    messagingSenderId: '628797668046',
    projectId: 'desk-relief',
    storageBucket: 'desk-relief.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbUG3I0QFRgGDQba7LmmTdP3tE-Zj_Yao',
    appId: '1:628797668046:ios:0d83cd91c4881f93582e9f',
    messagingSenderId: '628797668046',
    projectId: 'desk-relief',
    storageBucket: 'desk-relief.firebasestorage.app',
    androidClientId: '628797668046-j6tnd89s5f7627utncpg79lldkt9p6f0.apps.googleusercontent.com',
    iosClientId: '628797668046-7aqtnqr09j2touhegir3dlh0qifu4ood.apps.googleusercontent.com',
    iosBundleId: 'com.example.deskrelief',
  );

}